bot_token: 2147483647:c588c0a459f4ccc6f3dd26518d24707a
ban_time: 300
timeout: 300
log_chat_id: -1002147483647
custom_domain: www.example.com
default_lang: zh-hans
ban_regex: "(114514|1919810)"
chats:
  - chat_id: -10011111111
    questions:
      - question: Sample question 1?
        id: 1
        type: text
        answer: "regex01|regex(02|03)"
      - question: Sample question 2?
        id: 2
        type: text
        answer: "regex01|regex(02|03)"
  - chat_id: -10022222222
    questions:
      - question: Sample question 1?
        id: 1
        type: text
        answer: "regex01|regex(02|03)"
      - question: Sample question 2?
        id: 2
        type: text
        answer: "regex01|regex(02|03)"
